photoapp/urls.py
from django.urls import path
from . import views

app_name = 'photoapp'   #this is useful when someother app in this pro has same name ='detail', called as namespaces


urlpatterns = [
    path('', views.index , name = 'index'),
    path('<int:pk>/', views.detail , name = 'detail')
]

photopro/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include('photoapp.urls'))
]

photoapp/models.py
from django.db import models

# Create your models here.

class Photo(models.Model):
    name = models.CharField(max_length=200)
    creator = models.CharField(max_length=200)
    price = models.CharField(max_length=200)

    def __str__(self):
        return f"Photo no:- {self.id}"

photoapp/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404
from .models import Photo

# Create your views here.

def index(request):
    all_photos = Photo.objects.all()
    return render(request,'photoapp/photos.html',{'photos': all_photos})


def detail(request,pk):
    try:
        photo = Photo.objects.get(id=pk)  #getting a particular photo using that id
    except Photo.DoesNotExist:
        raise Http404("Photo not found") #raising an error if someone asks for a photo out of range

    return render(request,'photoapp/detail.html', {'photo': photo})

photoapp/templates/photoapp/detail.html
<!-- below gives the __str__ version defned in Photo Model -->
{% extends 'photoapp/photos.html'%}

{% block body_block%}
    <p>{{photo.name}}</p>
    <p>{{photo.price}}</p>
{% endblock %}

photoapp/templates/photoapp/photos.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All photos</title>
    <link rel="stylesheet" href="{% static 'photoapp/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'photoapp:index' %}" >
                    <span class="glyphicon glyphicon-camera"> Photos
                </a>
            </div>
        </div>
    </nav>

 
</body>

{% block body_block%}
        <h1>All the photos are below</h1>
        <br>
        
        <ul class='list'>
            {% for p in photos %}
            <li>
                <a class="list" href="{% url 'photoapp:detail' pk=p.id %}">{{p.name}}</a>
            </li>
            {% endfor %}
        </ul>
{% endblock %}
</html>